# Nombre que aparece en el navegador y en el título de la página
site_name: Documentación tarea UT0 PPS

# Lista de los enlaces a los archivos de documentación
nav:
  - Home: index.md
  - git: git.md
  - gitActions: gitActions.md
  - docker: docker.md
  - conclusiones: conclusiones.md

# Ruta de los archivos de documentación
doc_dir: docs 
